version: '3'

services:
  frontend:
    build: ./frontend
    restart: always
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - '3000:3000'
  api:
    build: ./api
    restart: always
    volumes:
      - /app/node_modules
      - ./api:/app
    ports:
      - '5555:5000'
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PORT: '3306'
      MYSQL_PASSWORD: password
      MYSQL_DB: time_db
  mysql:
    image: mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'
volumes:
  mysql_data:
